services:
  db:
    image: postgres:15-alpine
    container_name: gabarit-db
    restart: always
    environment:
      POSTGRES_USER: gabarit_user
      POSTGRES_PASSWORD: gabarit_password
      POSTGRES_DB: gabarit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
